name: Install nsis plugin
description: Install nsis plugin
branding:
  icon: check
  color: white
inputs:
  list:
    description: nsis plugin name list
    required: true
runs:
  using: composite
  steps:
    - name: install
      shell: pwsh
      run: |
        ./index.ps1 ${{ inputs.list }}
